# Generated by Django 5.0.4 on 2024-04-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_domain_cv_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_field', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='domain',
        ),
        migrations.AddField(
            model_name='cv',
            name='field_of_work',
            field=models.ManyToManyField(to='myapp.workfield'),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
