# Generated by Django 5.0.4 on 2024-04-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_workfield_remove_cv_domain_cv_field_of_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='field_of_work',
        ),
        migrations.AddField(
            model_name='cv',
            name='field_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.workfield'),
        ),
    ]
