# Generated by Django 5.0.4 on 2024-04-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_cv_field_of_work_cv_field_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='field_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.workfield'),
        ),
    ]
