# Generated by Django 5.0.4 on 2024-04-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='field_of_work',
            new_name='work_field',
        ),
    ]
